# Generated by Django 4.1.7 on 2023-03-06 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("full_name", "Full Name"),
                            ("job", "Job"),
                            ("email", "Email"),
                            ("domain_name", "Domain Name"),
                            ("phone_number", "Phone Number"),
                            ("company_name", "Company Name"),
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("address", "Address"),
                            ("date", "Date"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField()),
                ("range_start", models.IntegerField(blank=True, null=True)),
                ("range_end", models.IntegerField(blank=True, null=True)),
                ("sentences", models.IntegerField(blank=True, null=True)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schemas.dataschema",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
